IS_CUDA: True
LOG_LEVEL: 0

ANCHOR_IOU_THRESHOLD: 0.25
NUM_EPOCHS: 100
INPUT_SIZE: 416
BATCH_SIZE: 4
MIN_SCORE_THRESH: 0.1
MIN_IOU_THRESH: 0.5

LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.00001

IGNORE_THRESH: 0.5
ANCHORS:
  ANCHOR_S: [[10, 13], [16, 30], [33, 23]]
  ANCHOR_M: [[30, 61], [62, 45], [59, 119]]
  ANCHOR_L: [[116, 90], [156, 198], [373, 326]]

COEFFICIENT_COORD: 5.0
COEFFICIENT_NOOBJ: 0.2