IS_CUDA: True

NUM_EPOCHS: 50
INPUT_SIZE: 416
BATCH_SIZE: 12

LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.01

IGNORE_THRESH: 0.5
ANCHORS:
  ANCHOR_S: [[10, 13], [16, 30], [33, 23]]
  ANCHOR_M: [[30, 61], [62, 45], [59, 119]]
  ANCHOR_L: [[116, 90], [156, 198], [373, 326]]

COEFFICIENT_COORD: 5
COEFFICIENT_NOOBJ: 0.2