WEIGHT_PATH: null

ANCHOR_IOU_THRESHOLD: 0.25
NUM_EPOCHS: 160
INPUT_SIZE: 416
BATCH_SIZE: 32
LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.0005
LR_ADJUST_EPOCH: [60,90]

GET_PBR: False
AUGMENT_STRONG: 0.2
MAX_DETS: 100
MIN_SCORE_THRESH: 0.001
MIN_IOU_THRESH: 0.65

IGNORE_THRESH: 0.5
ANCHORS:
  ANCHOR_S: [[10, 13], [16, 30], [33, 23]]
  ANCHOR_M: [[30, 61], [62, 45], [59, 119]]
  ANCHOR_L: [[116, 90], [156, 198], [373, 326]]

COEFFICIENT_COORD: 5.0
COEFFICIENT_NOOBJ: 0.2
